INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gotowe naleśniki', 1, 1);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa Kamis', 1, 2);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('filet z piersi kurczaka', 1, 3);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchewka', 1, 4);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty ementaler', 1, 5);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kwaśna śmietana 18%', 1, 6);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('filet z kurczaka', 2, 7);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('brokuł', 2, 8);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawy Kamis', 2, 9);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser mozzarella', 2, 10);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 2, 11);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szczypiorek', 2, 12);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 36%', 2, 13);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 2, 14);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 2, 15);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 2, 16);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 2, 17);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda gazowana', 2, 18);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 2, 19);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mrożony szpinak', 3, 20);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos śmietanowy', 3, 21);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawy Kamis', 3, 22);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gotowe naleśniki', 3, 23);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mozzarella', 3, 24);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółty ser', 3, 25);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory z puszki', 3, 26);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 18%', 3, 27);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej do smażenia', 3, 28);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 3, 29);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka', 4, 30);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Rosół z kury', 4, 31);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 4, 32);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 4, 33);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchewka', 4, 34);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 4, 35);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 4, 36);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej do smażenia', 4, 37);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone wołowe', 5, 38);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory z puszki', 5, 39);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 5, 40);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 5, 41);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czerwona fasola z puszki', 5, 42);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kukurydza z puszki', 5, 43);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółty ser', 5, 44);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 5, 45);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda lub mleko', 5, 46);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 5, 47);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 5, 48);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 5, 49);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciasto francuskie', 6, 50);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Smażona cebula', 6, 51);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('parówki', 6, 52);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 6, 53);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 6, 54);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 6, 55);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółty ser', 6, 56);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 6, 57);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('wołowina gulaszowa', 7, 58);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do gulaszu węgierski', 7, 59);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 7, 60);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czerwona papryka', 7, 61);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('zielona papryka', 7, 62);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchewka', 7, 63);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('fasolka szparagowa', 7, 64);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka pietruszki', 7, 65);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej rzepakowy', 7, 66);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone wieprzowe', 8, 67);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciasto francuskie', 8, 68);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kajzerki', 8, 69);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 8, 70);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do mięsa mielonego', 8, 71);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 8, 72);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 8, 73);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szpinak', 8, 74);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 8, 75);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gałka muszkatołowa', 8, 76);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 8, 77);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka', 9, 78);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kasza pęczak', 9, 79);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kasza jęczmienna', 9, 80);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('soczewica czerwona lub zielona', 9, 81);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka', 9, 82);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sól', 9, 83);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa chili z wędzoną papryką', 9, 84);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 9, 85);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeże mango', 9, 86);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('prażone migdały', 9, 87);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kolendra', 9, 88);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('filet z kurczaka', 10, 89);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa uniwersalna Kamis', 10, 90);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron rurki', 10, 91);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 10, 92);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 10, 93);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('tarty ser', 10, 94);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana', 10, 95);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 10, 96);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapusta pekińska', 11, 97);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy czosnkowy', 11, 98);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 11, 99);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kukurydza', 11, 100);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka na twardo', 11, 101);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki konserwowe', 11, 102);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('majonez', 11, 103);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka pietruszki do dekoracji', 11, 104);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka', 12, 105);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukier', 12, 106);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jogurt naturalny', 12, 107);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 12, 108);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 12, 109);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 12, 110);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('aromat waniliowy', 12, 111);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka', 13, 112);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do mięs', 13, 113);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gotowe naleśniki', 13, 114);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti', 13, 115);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 13, 116);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana', 13, 117);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 13, 118);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 13, 119);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szynka', 14, 120);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 14, 121);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa uniwersalna Kamis', 14, 122);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 14, 123);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('margaryna', 14, 124);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka', 14, 125);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 14, 126);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 14, 127);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej słonecznikowy', 14, 128);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko 0,5% tłuszczu', 15, 129);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka', 15, 130);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 15, 131);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Rozdrobnione pomidory pelatti', 15, 132);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 15, 133);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 15, 134);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser gorgonzola', 15, 135);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('chudy twaróg', 15, 136);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej roślinny', 15, 137);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szpinak mrożony', 16, 138);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do zapiekanek makaronowych', 16, 139);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 16, 140);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 16, 141);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti', 16, 142);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('usmażone wcześniej naleśniki', 16, 143);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 22%', 16, 144);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 16, 145);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 16, 146);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do zapiekanek makaronowych z szynką', 17, 147);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szynka', 17, 148);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron penne', 17, 149);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('różyczki kalafiora', 17, 150);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('brokuł', 17, 151);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki koktajlowe', 17, 152);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 18%', 17, 153);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółty ser', 17, 154);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 17, 155);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory z puszki', 18, 156);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese Kamis', 18, 157);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 18, 158);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbki czosnku', 18, 159);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szpinak', 18, 160);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mozzarella', 18, 161);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda lub mleko', 18, 162);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 18, 163);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 18, 164);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 18, 165);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 18, 166);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka', 19, 167);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Bulion warzywny', 19, 168);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeży szpinak', 19, 169);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('starty ser żółty', 19, 170);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka słodka', 19, 171);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gałka muszkatołowa', 19, 172);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('masło', 19, 173);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kiełki', 19, 174);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 20, 175);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka pszenna', 20, 176);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jaja', 20, 177);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('roztopione masło', 20, 178);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('proszek do pieczenia', 20, 179);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukier', 20, 180);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('syrop klonowy', 20, 181);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cynamon', 20, 182);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 20, 183);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('masło do smażenia', 20, 184);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapusta pekińska', 21, 185);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy czosnkowy', 21, 186);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchew', 21, 187);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 21, 188);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cytryna', 21, 189);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 21, 190);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('chrzan', 21, 191);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka pietruszki', 21, 192);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sól', 21, 193);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukier', 21, 194);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory', 22, 195);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewka', 22, 196);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórki', 22, 197);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mix sałat', 22, 198);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapary', 22, 199);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy francuski', 22, 200);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 22, 201);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z pestek dyni', 22, 202);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('owoc granatu', 23, 203);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory', 23, 204);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek', 23, 205);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewka', 23, 206);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mix sałat', 23, 207);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża kolendra', 23, 208);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('koperek', 23, 209);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('orzechy włoskie', 23, 210);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 23, 211);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 23, 212);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sałata lodowa', 24, 213);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 24, 214);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka żółta', 24, 215);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka zielona', 24, 216);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek', 24, 217);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 24, 218);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki koktajlowe', 24, 219);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwki czarne', 24, 220);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 24, 221);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 24, 222);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 24, 223);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ocet balsamiczny', 24, 224);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos czosnkowo-ziołowy', 25, 225);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sałata lodowa', 25, 226);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rucola', 25, 227);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki koktajlowe', 25, 228);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czerwona cebula', 25, 229);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kiełki słonecznika', 25, 230);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeże ogórki', 26, 231);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 26, 232);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 26, 233);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('plastry sera feta', 26, 234);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone oregano', 26, 235);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukier', 26, 236);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 26, 237);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('dojrzałe awokado', 27, 238);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 27, 239);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki koktajlowe', 27, 240);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('upieczone lub ugotowane ziemniaki', 27, 241);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos majonezowo-czosnkowy', 27, 242);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża kolendra', 27, 243);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szpinak świeży', 28, 244);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 28, 245);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rukola', 28, 246);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 28, 247);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek zielony', 28, 248);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwki zielone', 28, 249);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 28, 250);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone oregano', 28, 251);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 28, 252);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sałata lodowa', 29, 253);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 29, 254);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czerwona cebula', 29, 255);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 29, 256);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone oregano', 29, 257);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 29, 258);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 29, 259);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki cherry', 30, 260);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mozzarella', 30, 261);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 30, 262);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rukola', 30, 263);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pestki słonecznika', 30, 264);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 30, 265);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 30, 266);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cykoria', 31, 267);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 31, 268);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('garść mieszanej sałaty (radicchio, lodowej i rukoli)', 31, 269);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewka', 31, 270);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek świeży', 31, 271);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('garść kiełków słonecznika', 31, 272);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka przepiórcze', 31, 273);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szczypior od dymki', 31, 274);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sok z cytryny', 31, 275);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 31, 276);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchewka', 32, 277);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy francuski', 32, 278);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek zielony', 32, 279);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki cherry', 32, 280);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('główka sałaty lodowej', 32, 281);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewka', 32, 282);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kiełki lucerny', 32, 283);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 32, 284);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mini kulki mozzarelli', 32, 285);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 32, 286);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapusta pekińska', 33, 287);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy francuski', 33, 288);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ziemniaki', 33, 289);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kiszone ogórki', 33, 290);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szczypiorek', 33, 291);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 33, 292);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 33, 293);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mandarynki z puszki lub filety z pomarańczy', 34, 294);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('seler naciowy, łodygi', 34, 295);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('migdały', 34, 296);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('piersi z kurczaka', 34, 297);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do mięs', 34, 298);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 34, 299);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cykorie', 34, 300);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółty ser', 34, 301);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża kolendra', 34, 302);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sos tabasco kilka kropel', 34, 303);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szparagi', 35, 304);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 35, 305);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szynka dojrzewająca', 35, 306);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('botwinka', 35, 307);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewka', 35, 308);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mix sałat', 36, 309);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 36, 310);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 36, 311);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidor', 36, 312);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 36, 313);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czerwona cebula', 36, 314);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwki czarne', 36, 315);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 36, 316);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 36, 317);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka pietruszki', 36, 318);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gałązki świeżego rozmarynu', 36, 319);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbki czosnku', 36, 320);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sałata masłowa', 37, 321);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek', 37, 322);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewki', 37, 323);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 37, 324);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szczypiorek', 37, 325);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 37, 326);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jogurt naturalny', 37, 327);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cytryna', 37, 328);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ziemniaki średnie', 38, 329);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do pikantnego kurczaka', 38, 330);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy francuski', 38, 331);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szparagi zielone', 38, 332);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szparagi białe', 38, 333);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kalarepa', 38, 334);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mix sałat', 38, 335);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieprz czarny mielony', 38, 336);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 38, 337);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej rzepakowy do smażenia', 38, 338);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 38, 339);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 39, 340);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy grecki', 39, 341);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos majonezowy', 39, 342);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka zielona', 39, 343);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('paluszki krabowe', 39, 344);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bakłażan', 39, 345);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 39, 346);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwki czarne', 39, 347);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwki zielone', 39, 348);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 39, 349);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bagietka', 39, 350);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 39, 351);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kukurydza z puszki', 40, 352);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 40, 353);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki koktajlowe', 40, 354);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 40, 355);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kozi ser', 40, 356);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bazylia świeża', 40, 357);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 40, 358);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sok z cytryny', 40, 359);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 41, 360);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czosnek ząbki', 41, 361);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Lasagne', 41, 362);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone wołowe', 41, 363);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czerwone wino', 41, 364);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('koncentrat pomidorowy', 41, 365);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron Lasagne', 41, 366);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 41, 367);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 41, 368);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('masło', 41, 369);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 41, 370);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gałka muszkatołowa', 41, 371);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 41, 372);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 41, 373);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron lasagne', 42, 374);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 42, 375);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty lub mozzarella', 42, 376);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser feta', 42, 377);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 42, 378);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bakłażany', 42, 379);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mielona wołowina', 42, 380);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('passata pomidorowa', 42, 381);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cynamon', 42, 382);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kwaśna śmietana lub jogurt grecki', 42, 383);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej rzepakowy', 42, 384);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron lasagne', 43, 385);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone wołowe', 43, 386);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 43, 387);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mrożona mieszanka warzyw', 43, 388);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('przecier pomidorowy', 43, 389);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser mozzarella lub inny żółty ser', 43, 390);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 43, 391);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone', 44, 392);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 44, 393);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron lasagne', 44, 394);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 18%', 44, 395);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory pelati w puszce', 44, 396);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('starty ser', 44, 397);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej roślinny do smażenia', 44, 398);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone', 45, 399);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 45, 400);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron Lasagne', 45, 401);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szpinak mrożony', 45, 402);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 45, 403);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 45, 404);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone oregano', 45, 405);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('przecier pomidorowy', 45, 406);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 45, 407);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('gałka muszkatołowa', 45, 408);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieprz czarny mielony', 45, 409);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 45, 410);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('masło', 45, 411);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 45, 412);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 18%', 45, 413);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone', 46, 414);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 46, 415);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron lasagne', 46, 416);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana gęsta', 46, 417);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory z puszki', 46, 418);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('starty ser', 46, 419);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej roślinny do smażenia', 46, 420);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mielone mięso drobiowe', 47, 421);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('wędzona szynka drobiowa', 47, 422);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Lasagne', 47, 423);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron lasagne', 47, 424);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółty ser', 47, 425);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory suszone', 47, 426);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czosnek w ząbkach', 47, 427);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 47, 428);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sól do smaku', 47, 429);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieprz czarny mielony', 47, 430);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('masło', 47, 431);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa do smażenia', 47, 432);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 47, 433);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 48, 434);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('tuńczyk w sosie własnym', 48, 435);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapary', 48, 436);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 48, 437);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory pelati', 48, 438);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 48, 439);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory', 48, 440);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 48, 441);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('awokado', 48, 442);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 18%', 48, 443);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża bazylia', 48, 444);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron lasagne', 48, 445);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 48, 446);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ziemniaki', 49, 447);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Lasagne', 49, 448);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone', 49, 449);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('boczek wędzony', 49, 450);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 49, 451);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('majeranek', 49, 452);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('koncentrat pomidorowy', 49, 453);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('parmezan starty', 49, 454);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieprz czarny mielony', 49, 455);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron Lasagne', 50, 456);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Carbonara', 50, 457);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Makaron Lasagne', 50, 458);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mielona wołowina', 50, 459);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('koncentrat pomidorowy', 50, 460);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('wędzony boczek', 50, 461);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 50, 462);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchew', 50, 463);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('seler naciowy łodyga', 50, 464);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory', 50, 465);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 50, 466);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser cheddar', 50, 467);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('parmezan', 50, 468);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('tymianek suszony', 50, 469);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bazylia', 50, 470);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone oregano', 50, 471);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda w miarę potrzeb', 50, 472);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 50, 473);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('piersi z kurczaka', 51, 474);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Ketchup', 51, 475);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Mieszanka potraw chińskich', 51, 476);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron jajeczny lub spaghetti', 51, 477);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('orzeszki ziemne', 51, 478);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('chińska mieszanka mrożonych warzyw', 51, 479);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej roślinny', 51, 480);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron spaghetti', 52, 481);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Carbonara', 52, 482);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 36%', 52, 483);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieprz czarny mielony', 52, 484);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser do posypania', 52, 485);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 52, 486);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron spaghetti', 53, 487);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka', 53, 488);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Świderki z kurczakiem w sosie serowym', 53, 489);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 53, 490);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 53, 491);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża bazylia', 53, 492);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana', 53, 493);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('parmezan lub inny ser o zdecydowanym smaku', 53, 494);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('orzeszki pinii', 53, 495);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron tagliatelle', 54, 496);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 54, 497);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mielona wołowina', 54, 498);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('krojone pomidory z puszki', 54, 499);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mozzarella', 54, 500);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 54, 501);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża bazylia', 54, 502);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej rzepakowy', 54, 503);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron spaghetti', 55, 504);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeży lub mrożony szpinak', 55, 505);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 55, 506);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory z puszki', 55, 507);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana', 55, 508);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 55, 509);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbki czosnku', 55, 510);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 55, 511);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron spaghetti', 56, 512);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('krojone pomidory z puszki', 56, 513);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 56, 514);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 56, 515);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka', 56, 516);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 56, 517);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 56, 518);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('garść świeżej bazylii', 56, 519);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 56, 520);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cukinia', 57, 521);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marchewka', 57, 522);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 57, 523);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Rosół z kury', 57, 524);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 57, 525);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory krojone z puszki', 57, 526);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapary', 57, 527);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('orzeszki pinii', 57, 528);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 57, 529);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('wegańska alternatywa parmezanu', 57, 530);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('zioła prowansalskie', 57, 531);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 57, 532);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka pietruszki', 57, 533);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mięso mielone', 58, 534);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do Spaghetti Bolognese', 58, 535);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron spaghetti', 58, 536);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory z puszki', 58, 537);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej', 58, 538);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 58, 539);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('filety z piersi kurczaka', 59, 540);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Świderki z kurczakiem w sosie serowym', 59, 541);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron tagliatelle', 59, 542);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 59, 543);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 59, 544);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 59, 545);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('musztarda', 59, 546);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża natka pietruszki', 59, 547);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej rzepakowy', 59, 548);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('filety z piersi kurczaka', 60, 549);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Rosół z kury', 60, 550);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makaron penne', 60, 551);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki', 60, 552);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 60, 553);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa uniwersalna Kamis', 60, 554);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('woda', 60, 555);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śmietana 18%', 60, 556);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka pszenna', 60, 557);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej do smażenia', 60, 558);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mała natka pietruszki', 60, 559);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('starty parmezan lub inny żółty ser', 60, 560);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 61, 561);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone oregano', 61, 562);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 61, 563);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('małe pomidory', 61, 564);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 61, 565);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('anchois', 61, 566);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bagietka pszenna', 61, 567);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('chleb typu panini', 62, 568);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Bulion warzywny', 62, 569);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szynka', 62, 570);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 62, 571);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory', 62, 572);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 62, 573);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bazylia', 62, 574);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwki czarne', 62, 575);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rukola', 62, 576);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 62, 577);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczywo na grzanki', 63, 578);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory', 63, 579);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('tuńczyk z puszki w zalewie własnej', 63, 580);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa w kostkach', 63, 581);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szalotki', 63, 582);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża bazylia', 63, 583);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 63, 584);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sok z połowy cytryny', 63, 585);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 63, 586);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('polędwiczka wieprzowa', 64, 587);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do gyrosa', 64, 588);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kiszona kapusta', 64, 589);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebule', 64, 590);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzeżucha', 64, 591);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 64, 592);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 64, 593);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kminek', 64, 594);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('chleb razowy pełnoziarnisty', 64, 595);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Ketchup', 64, 596);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('masło lub margaryna', 64, 597);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bakłażan', 65, 598);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Ketchup', 65, 599);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 65, 600);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('czosnek, główka', 65, 601);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('olej sezamowy', 65, 602);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka kolendry', 65, 603);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sos sojowy', 65, 604);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bagietka pełnoziarnista', 65, 605);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 65, 606);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka żółta', 65, 607);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kromka pieczywa', 66, 608);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 66, 609);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('starty cheddar', 66, 610);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('creme fraiche', 66, 611);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('żółtko', 66, 612);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sos Worcestershire', 66, 613);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('musztarda', 66, 614);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mąka', 66, 615);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 66, 616);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('marmolada chilli', 66, 617);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciemne pieczywo tostowe', 67, 618);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 67, 619);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka z rosołu', 67, 620);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szpinak świeży', 67, 621);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 67, 622);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szczypiorek', 67, 623);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 67, 624);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciabatta', 68, 625);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Ketchup', 68, 626);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 68, 627);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczarki portobello', 68, 628);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidor', 68, 629);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 68, 630);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sałata rucola', 68, 631);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser mozzarella', 68, 632);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bagietka', 69, 633);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('twarożek kanapkowy', 69, 634);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('przyprawa uniwersalna Kamis', 69, 635);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('starty parmezan', 69, 636);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('suszone pomidory', 69, 637);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża bazylia', 69, 638);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeży tymianek', 69, 639);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 69, 640);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieprz czarny mielony', 69, 641);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidory cherry', 70, 642);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 70, 643);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pęczek bazylii', 70, 644);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bagietka', 70, 645);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 70, 646);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ocet balsamiczny', 70, 647);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 70, 648);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('biała fasola', 71, 649);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 71, 650);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jabłko', 71, 651);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('śliwki suszone, najlepiej polskie wędzone', 71, 652);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('liść laurowy', 71, 653);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbki czosnku', 71, 654);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ziele angielskie', 71, 655);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 71, 656);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('majeranek', 71, 657);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('lubczyk', 71, 658);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 72, 659);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('makrela wędzona', 72, 660);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka', 72, 661);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ogórek konserwowy', 72, 662);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pestki słonecznika', 72, 663);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szczypior', 72, 664);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka ostra w proszku, mielona', 72, 665);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cytryna', 72, 666);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciabatta', 73, 667);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos sałatkowy włoski', 73, 668);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser twarogowy, np. kozi', 73, 669);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szynka', 73, 670);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidorki cherry', 73, 671);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeżo mielony czarny pieprz', 73, 672);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 73, 673);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kilka listków sałaty', 73, 674);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kajzerki', 74, 675);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko', 74, 676);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('boczek w plastrach', 74, 677);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 74, 678);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jogurt', 74, 679);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cytryna', 74, 680);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa uniwersalna', 74, 681);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mleko', 74, 682);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('musztarda', 74, 683);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ocet', 74, 684);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('chleb z ziarnami, kromki', 75, 685);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciecierzyca z puszki', 75, 686);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kmin rzymski', 75, 687);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('majeranek', 75, 688);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('goździki', 75, 689);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jabłko', 75, 690);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula', 75, 691);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 75, 692);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa', 75, 693);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('syrop klonowy', 75, 694);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sos sojowy', 75, 695);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bajgle', 76, 696);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pesto z bazylii', 76, 697);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez', 76, 698);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka 300g', 76, 699);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kapary', 76, 700);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mała czerwona cebula', 76, 701);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ostra papryczka chilli', 76, 702);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('natka kolendry', 76, 703);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajka', 76, 704);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('liść sałaty lodowej', 76, 705);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rzodkiewka', 76, 706);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczywo tostowe pełnoziarniste, kromki', 77, 707);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Majonez Hellmann''s Oryginalny', 77, 708);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('jajko ugotowane na twardo', 77, 709);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 77, 710);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('posiekany szczypiorek', 77, 711);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ciabatta', 78, 712);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos majonezowy', 78, 713);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pomidor', 78, 714);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('mozzarella', 78, 715);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 78, 716);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rukola', 78, 717);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('sól', 78, 718);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pieczywo tostowe, kromki', 79, 719);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('szynka konserwowa', 79, 720);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ananas z puszki', 79, 721);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Sos majonezowy', 79, 722);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ser żółty', 79, 723);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('posiekana natka pietruszki', 79, 724);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bułka orkiszowa', 80, 725);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('pierś z kurczaka pojedyncza', 80, 726);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('Przyprawa do złotego kurczaka', 80, 727);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryka czerwona', 80, 728);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('bakłażan', 80, 729);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('ząbek czosnku', 80, 730);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('cebula czerwona', 80, 731);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('oliwa z oliwek', 80, 732);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('papryczka chilli', 80, 733);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('świeża kolendra', 80, 734);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('kiełki słonecznika', 80, 735);
INSERT INTO ingredient(name, recipe_id, amount_id) VALUES ('rukola', 80, 736);
