INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki z kurczakiem w sosie bolognese', 35, '/recipes/recipe1.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki z brokułami i kurczakiem', 50, '/recipes/recipe2.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki zapiekane po bolońsku', 55, '/recipes/recipe3.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kurczak duszony z warzywami', 25, '/recipes/recipe4.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki a la buritos', 45, '/recipes/recipe5.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Parówki w cieście francuskim z warzywami', 30, '/recipes/recipe6.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Gulasz z fasolką szparagową i warzywami', 60, '/recipes/recipe7.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kotlety mielone wellington z warzywami', 30, '/recipes/recipe8.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Rozgrzewająca sałatka w papryce', 30, '/recipes/recipe9.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Makaron z kurczakiem i pieczarkami', 30, '/recipes/recipe10.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kapusta pekińska z jajkiem i kukurydzą', 15, '/recipes/recipe11.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Mini placuszki z nutellą', 30, '/recipes/recipe12.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki z kurczakiem i pieczarkami', 45, '/recipes/recipe13.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki z szynką i pieczarkami', 30, '/recipes/recipe14.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki z cukinią i serem', 30, '/recipes/recipe15.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki ze szpinakiem', 45, '/recipes/recipe16.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Zapiekanka z szynką i warzywami', 60, '/recipes/recipe17.jpg', 1, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Naleśniki ze szpinakiem i serem na sosie pomidorowym', 30, '/recipes/recipe18.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Jajka faszerowane szpinakiem', 30, '/recipes/recipe19.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Amerykańskie naleśniki (pancakes)', 30, '/recipes/recipe20.jpg', 1, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka coleslaw z kapusty pekińskiej', 15, '/recipes/recipe21.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Szybka sałatka na grilla', 15, '/recipes/recipe22.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Smaczna sałatka na grilla z pestkami granatu', 15, '/recipes/recipe23.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka grecka z sałatą lodową', 20, '/recipes/recipe24.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Letnia sałatka na grilla', 15, '/recipes/recipe25.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka ze świeżych ogórków z serem feta', 25, '/recipes/recipe26.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Szybka sałatka na grilla z suszonymi pomidorami i awokado', 15, '/recipes/recipe27.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka zielona', 15, '/recipes/recipe28.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Prosta sałatka na grilla', 15, '/recipes/recipe29.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka z rukolą i mozzarellą', 15, '/recipes/recipe30.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Wiosenna sałatka z rzodkiewką', 30, '/recipes/recipe31.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka tagliatelle warzywne', 30, '/recipes/recipe32.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka z kapusty pekińskiej', 50, '/recipes/recipe33.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka z kurczaka i mandarynek', 30, '/recipes/recipe34.jpg', 2, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka szparagowa', 15, '/recipes/recipe35.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałata z pieczoną papryką, oliwkami i serem feta', 60, '/recipes/recipe36.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Wiosenna sałata ze szczypiorkiem', 15, '/recipes/recipe37.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka z młodych ziemniaków', 45, '/recipes/recipe38.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Grecka sałatka z grillowanych warzyw z krabowymi paluszkami i grzankami z sosem czosnkowym', 30, '/recipes/recipe39.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Sałatka piknikowa', 15, '/recipes/recipe40.jpg', 2, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lasagne', 60, '/recipes/recipe41.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lazania po grecku', 60, '/recipes/recipe42.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lazania z mięsem i warzywami', 45, '/recipes/recipe43.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lasagne', 45, '/recipes/recipe44.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lazania z mięsem mielonym i szpinakiem', 60, '/recipes/recipe45.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Klasyczna lasagne', 60, '/recipes/recipe46.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lasagne z mięsa mielonego drobiowego', 60, '/recipes/recipe47.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lasagne z tuńczykiem', 45, '/recipes/recipe48.jpg', 3, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Lazania farmera', 60, '/recipes/recipe49.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Włoska lasagne z pieczarkami', 90, '/recipes/recipe50.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Smażony makaron', 30, '/recipes/recipe51.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Szybkie spaghetti carbonara', 20, '/recipes/recipe52.jpg', 3, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Spaghetti w bazyliowym sosie', 30, '/recipes/recipe53.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Makaron tagliatelle z sosem bolognese i mozzarellą', 30, '/recipes/recipe54.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Spaghetti z pomidorami i szpinakiem po neapolitańsku', 45, '/recipes/recipe55.jpg', 3, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Spaghetti bolognese z warzywami i pieczarkami', 30, '/recipes/recipe56.jpg', 3, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Spaghetti z cukinii i marchewki', 35, '/recipes/recipe57.jpg', 3, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Spaghetti bolognese', 30, '/recipes/recipe58.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Makaron w sosie pieczarkowym', 20, '/recipes/recipe59.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Makaron z kurczakiem i sosem śmietanowym', 45, '/recipes/recipe60.jpg', 3, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Grzanki po neapolitańsku', 30, '/recipes/recipe61.jpg', 4, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Włoskie panini z szynką i serem', 30, '/recipes/recipe62.jpg', 4, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Bruschetta z tuńczykiem pomidorami i bazylią', 15, '/recipes/recipe63.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kanapka gyros', 45, '/recipes/recipe64.jpg', 4, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kanapka z pieczonymi warzywami', 45, '/recipes/recipe65.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Grzanki z serem po walijsku', 30, '/recipes/recipe66.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Grillowane tosty z kurczakiem', 15, '/recipes/recipe67.jpg', 4, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Ciabatta z grillowanymi warzywami', 30, '/recipes/recipe68.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Crostini z serem', 15, '/recipes/recipe69.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Bruschetta z marynowanymi pomidorami', 15, '/recipes/recipe70.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Wegetariański smalec z białej fasoli i jabłka', 30, '/recipes/recipe71.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kanapki z pastą rybną z jajkiem i ogórkiem konserwowym', 15, '/recipes/recipe72.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Ciabatta z serem', 15, '/recipes/recipe73.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Jajka a la po benedyktyńsku na szybko', 15, '/recipes/recipe74.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Pełnoziarniste kanapki z wegańskim smalcem z cieciorki', 20, '/recipes/recipe75.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Bajgiel z hamburgerem z kurczaka i sadzonym jajkiem', 10, '/recipes/recipe76.jpg', 4, 'MEAT');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kanapka z pastą jajeczną z papryką i szczypiorkiem', 15, '/recipes/recipe77.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kanapka włoska', 15, '/recipes/recipe78.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Kanapka hawajska z szynką i ananasem', 15, '/recipes/recipe79.jpg', 4, 'VEGETARIAN');
INSERT INTO recipe (title, prep_time, image_url, category_id, meal_type) VALUES ('Chrupiąca orkiszowa kanapka z kurczakiem i pastą warzywną', 25, '/recipes/recipe80.jpg', 4, 'MEAT');
