spring:
  jpa:
    show-sql: true
  web:
    resources:
      static-locations: classpath:/static,file:images/
kulinaria:
  pathPrefix: file:C:\Users\Maciek\Javastart\Portfolio\Kulinaria
logging:
  level:
    org.springframework.security.web: DEBUG
    com.com.kulinaria: DEBUG